volumes:
  client-files:

services:
  client:
    build:
      context: ./client
    container_name: client
    volumes:
      # Mount /data folder from client container to client-files volume
      - client-files:/data

  proxy:
    build: ./proxy
    container_name: proxy
    volumes:
      # Mount /usr/share/nginx/html from proxy container to client-files volume
      # but with read-only access
      - client-files:/usr/share/nginx/html:ro
    ports:
      - "80:80"

  server:
      build:
        context: ./server
      container_name: server

networks:
  default:
